# Generated by Django 5.2.9 on 2025-12-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estado',
            field=models.CharField(choices=[('reagendar', 'Reagendar'), ('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida')], default='pendiente', max_length=20),
        ),
    ]
