# Generated by Django 5.2.9 on 2025-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Cliente'), ('STAFF', 'Staff de Óptica'), ('ADMIN', 'Administrador')], default='CLIENT', max_length=20),
        ),
    ]
